### Request 1
POST http://localhost:8000/store/users/ HTTP/1.1
content-type: application/json

{
    "name": "Jan Lechowski"
}

### signup
POST http://localhost:8000/store/signup/ HTTP/1.1
content-type: application/json

{
    "username": "JJ", "password": "123"
}

### login
POST http://localhost:8000/store/login/ HTTP/1.1
content-type: application/json

{
    "username": "jlp", "password": "pbkdf2_sha256$260000$ManImD3snLJCPK3LNyjk0p$cta1MpLjABFAiDjrK9fiiFLk/QjDYdCpaji0CSU719M="
}


### login
GET http://localhost:8000/store/users/ HTTP/1.1
content-type: application/json
Authorization: Token e5eee6fff89bbc17d7c385205d172189a0564813

{}
